edit workflow

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -68,7 +68,7 @@ jobs:
       - name: Run Stylelint
         run: |
           echo "Running Stylelint..."
-          npx stylelint "**/*.css" "**/*.scss" "**/*.sass" --config stylelintrc.json || echo "Stylelint errors found"
+          npx stylelint "**/*.css" "**/*.scss" "**/*.sass" --config stylelintrc.json > stylelint-errors.txt 2>&1 || echo "Stylelint errors found" >> stylelint-errors.txt
           [ -s stylelint-report.txt ] || echo "No Stylelint issues found." > stylelint-report.txt
           cat stylelint-report.txt
 
