edit workflow

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -68,7 +68,7 @@ jobs:
       - name: Run Stylelint
         run: |
           echo "Running Stylelint..."
-          npx stylelint "**/*.css" "**/*.scss" "**/*.sass" --config stylelintrc.json --output-file stylelint-report.txt || echo "Stylelint errors found" --output-file stylelint-report.txt
+          npx stylelint "**/*.css" "**/*.scss" "**/*.sass" --config stylelintrc.json > stylelint-report.txt || echo "Stylelint errors found" > stylelint-report.txt
           [ -s stylelint-report.txt ] || echo "No Stylelint issues found." --output-file stylelint-report.txt
           cat stylelint-report.txt
 
